# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  lint:
    cmds:
      - golangci-lint run ./...
  sqlc:
    cmds:
      - sqlc generate
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
