services:
  database:
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - dev.env
    image: postgres:16.2-alpine3.19
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - database:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_s3
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"  # API endpoint (S3)
    networks:
      - minio_net

networks:
  minio_net:
    driver: bridge

volumes:
  minio_data:
    driver: local
  database:
